# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: ecotrackapi
services:
  eco:
    image: docker.jojoaddison.net/ecotrack-app
    container_name: app
    ports:
      - '127.0.0.1:4820:80'
    environment:
      - NODE_ENV=production
      - production=true
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost/health']
      interval: 60s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - devnet
    depends_on:
      - api
  api:
    image: ecotrackapi
    container_name: ecotrackapi
    hostname: ecotrackapi
    env_file: .env
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ecotrackApi
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/ecotrackApi
      - SPRING_LIQUIBASE_USERNAME=postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DOCKER_COMPOSE_ENABLED=false
    ports:
      - 127.0.0.1:2026:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    networks:
      - devnet

networks:
  devnet:
    name: devnet
    external: true
